### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by IrynaBedryk** [IrynaBedryk/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by AsiaOkun** [comment]
```Hello.It is great for me to become a member of the GitHub community (just a little bit_;) at the moment). It's cool to study new, amazing and interesting technologies in order to make an informational world around us better ```

**Comment by AsiaOkun** [comment]
Education
Every Day 
Fundamentals of testing, SDLC, Software Development Models, Tools for testing, Python (basic), HTML, CSS
December 2018 – March 2019
Certificate of completion of Software testing training for absolute beginners (ISTQB Masterclass) at Udemy
November 2018
Certificate in Basic of Software Testing at  Prometheus
May 2014 
Ph D in Technical Sciences 
November 2010 – October 2013
Certificate of graduation at Postgraduate School at Odessa State Academy of Civil Engineering and Architecture
September 2009-February 2011
Masters in Management of Projects (Managing Director of Projects and Programs) at Odessa State Academy of Civil 
September 2009-June 2010
Masters in Civil Engineering (Industrial and Civil Construction) at Odessa State Academy of Civil Engineering and Architecture
September 2005 – June 2009
Bachelor in Civil Engineering (Industrial and Civil Construction) at Odessa State Academy of Civil Engineering and Architecture

WANTS
Building great career in QA
To work in Elon Musk’s company
To be fit, nice and healthy
To write a book (maybe a few)
Daily own development and work on myself

DISLIKES
Bugs, stupid reality show, high-hat, selfy, state of science in Ukraine, doing nothing

LIKES

Busy schedule, take a rest after good results of the job, foreign languages, classic music and eminem, early stand up, watching the sea and thunderstorm

CHARACTER
Attentive, disciplined, meticulous, prompt, realistic, motivated, organized, hardworking, energetic, procrastinator

SKILLS
HTML CSS Python(basic) SQL JIRA TestRail Postman(basic) Agile Scrum AUTOCAD

LANGUAGES
Ukrainian, Russian, English

**Comment by IrynaBedryk** [comment]
Thanks a lot
